import React, { useState, useEffect, useRef, useMemo } from 'react';
import './laser_dot.css';
import { useConnection } from '../components/context/ConnectionContext';
import { uploadGcodeFile } from '../components/api/gcodeUploader';

// --- Bed configuration (origin at bottom center, matches plotter convention) ---
const BED_WIDTH_MM = 500;
const BED_HEIGHT_MM = 300;
const BED_CENTER_X_MM = 250;

const DEFAULT_SETTINGS = {
  // Dimensions (mm)
  width: 100,
  height: 100,
  keepProportions: true,

  // Position (posX: -250..+250 from center, posY: 0 = bottom)
  posX: 0,
  posY: 0,

  // Dot engraving
  dotSpacing: 0.5,        // mm between dots
  laserPower: 1000,       // Max S value (used for a fully black pixel). Lighter pixels get a proportionally lower S.
  dwell: 30,              // ms — fixed dwell time used for every dot
  whiteThreshold: 240,    // 0..255 — pixels brighter are skipped (no burn)
  invert: false,          // negative image
  zigzag: true,           // alternate row direction (faster travel)
  travelSpeed: 6000,      // mm/min
  dwellUnit: 'ms',        // 'ms' (Marlin: G4 P<ms>) or 's' (GRBL: G4 P<sec>)
  workZ: 0,               // mm — Z height used for dot engraving
};

function createItemId() {
  return 'ldot_' + Date.now() + '_' + Math.random().toString(36).slice(2, 9);
}

function round1(num) {
  if (typeof num !== 'number' || Number.isNaN(num)) return num;
  return Math.round(num * 10) / 10;
}

function clamp(v, a, b) {
  return Math.min(Math.max(v, a), b);
}

// --- Image -> dot grid ---
// For each (col,row) cell of size dotSpacing × dotSpacing, sample average grayscale.
// Skip pixels brighter than whiteThreshold. Store normalized darkness (0..1)
// per dot so the per-dot laser S-value can be derived later as
// S = round(darkness * laserPower) — black pixel => full power, lighter
// pixel => proportionally lower power.
function imageToDotGrid(imageEl, settings) {
  const cols = Math.max(1, Math.floor(settings.width / settings.dotSpacing));
  const rows = Math.max(1, Math.floor(settings.height / settings.dotSpacing));
  if (!imageEl || cols <= 0 || rows <= 0) return { dots: [], cols, rows };

  const canvas = document.createElement('canvas');
  canvas.width = cols;
  canvas.height = rows;
  const ctx = canvas.getContext('2d');
  ctx.drawImage(imageEl, 0, 0, cols, rows);
  const imageData = ctx.getImageData(0, 0, cols, rows);
  const px = imageData.data;

  const dots = [];
  const wt = clamp(settings.whiteThreshold, 1, 255);
  for (let r = 0; r < rows; r++) {
    for (let c = 0; c < cols; c++) {
      const i = (r * cols + c) * 4;
      let lum = 0.299 * px[i] + 0.587 * px[i + 1] + 0.114 * px[i + 2];
      if (settings.invert) lum = 255 - lum;
      if (lum >= wt) continue;
      const darkness = (wt - lum) / wt; // 1 = black, 0 = at threshold
      dots.push({ c, r, darkness, lum });
    }
  }
  return { dots, cols, rows };
}

// --- G-code generator ---
function generateLaserDotGCode(items) {
  const lines = [];
  lines.push('; Generated by Laser Dot Engraver');
  lines.push('G21 ; units = mm');
  lines.push('G90 ; absolute positioning');
  lines.push('M5 ; laser off');

  items.forEach((item, idx) => {
    const s = item.settings;
    const grid = item.grid;
    if (!grid || grid.dots.length === 0) return;

    lines.push(`; --- Image ${idx + 1}: ${item.name} (${grid.dots.length} dots) ---`);
    lines.push(`G0 F${s.travelSpeed}`);
    lines.push(`G0 Z${(s.workZ ?? 0).toFixed(3)}`);

    // Group dots by row, then traverse rows top-to-bottom with zigzag X direction.
    const byRow = new Map();
    grid.dots.forEach((d) => {
      if (!byRow.has(d.r)) byRow.set(d.r, []);
      byRow.get(d.r).push(d);
    });
    const rows = [...byRow.keys()].sort((a, b) => a - b);

    // Fixed dwell for every dot (user-set value, same for the whole job)
    const dwellMs = Math.max(1, Math.round(s.dwell));
    const dwellOut = s.dwellUnit === 's'
      ? (dwellMs / 1000).toFixed(3)
      : dwellMs;

    let leftToRight = true;
    rows.forEach((r) => {
      const rowDots = byRow.get(r);
      rowDots.sort((a, b) => a.c - b.c);
      const ordered = (s.zigzag && !leftToRight) ? rowDots.slice().reverse() : rowDots;
      ordered.forEach((d) => {
        // Convert grid (c,r) to bed mm.
        // Image origin = top-left of placed image.
        // Bed: posX is left edge of image (in centered coords), posY is bottom edge.
        // Top-left of image in bed coords: x = posX, y = posY + height.
        const xMm = s.posX + d.c * s.dotSpacing + s.dotSpacing / 2;
        const yMm = s.posY + s.height - (d.r * s.dotSpacing + s.dotSpacing / 2);
        // Scale laser S by pixel darkness: black => s.laserPower, lighter => proportionally less.
        const sVal = Math.max(1, Math.min(65535, Math.round(d.darkness * s.laserPower)));
        lines.push(`G0 X${xMm.toFixed(3)} Y${yMm.toFixed(3)}`);
        lines.push(`M3 S${sVal}`);
        lines.push(`G4 P${dwellOut}`);
        lines.push('M5');
      });
      leftToRight = !leftToRight;
    });
  });

  lines.push('M5 ; laser off');
  lines.push('G0 X0 Y0');
  lines.push('M2 ; program end');
  return lines.join('\n');
}

// --- Visual: render preview dots on a canvas (each dot sized by dwell) ---
function DotPreview({ item, scale, isSelected }) {
  const canvasRef = useRef(null);
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas || !item || !item.grid) return;
    const { settings, grid } = item;
    const renderScale = 2;
    canvas.width = Math.max(1, settings.width * renderScale);
    canvas.height = Math.max(1, settings.height * renderScale);
    const ctx = canvas.getContext('2d');
    ctx.scale(renderScale, renderScale);
    ctx.clearRect(0, 0, settings.width, settings.height);

    // Background: light tint to show image area
    ctx.fillStyle = 'rgba(255,255,255,0.9)';
    ctx.fillRect(0, 0, settings.width, settings.height);

    if (!grid.dots.length) return;

    const sp = settings.dotSpacing;

    grid.dots.forEach((d) => {
      const x = d.c * sp + sp / 2;
      const y = d.r * sp + sp / 2;
      // Dot radius and opacity scale with darkness — i.e. with the laser S
      // value that will actually be emitted (S = darkness * laserPower).
      const t = clamp(d.darkness, 0, 1);
      const rad = Math.max(sp * 0.15, sp * (0.25 + 0.55 * t));
      ctx.beginPath();
      ctx.arc(x, y, rad, 0, Math.PI * 2);
      ctx.fillStyle = `rgba(17,17,17,${0.35 + 0.65 * t})`;
      ctx.fill();
    });
  }, [item.grid, item.settings.width, item.settings.height, item.settings.dotSpacing]);

  const { settings } = item;
  return (
    <div
      data-ldot-item
      data-id={item.id}
      style={{
        position: 'absolute',
        left: `${(BED_CENTER_X_MM + settings.posX) * scale}px`,
        top: `${(BED_HEIGHT_MM - settings.posY - settings.height) * scale}px`,
        width: `${settings.width * scale}px`,
        height: `${settings.height * scale}px`,
        border: isSelected ? '2px dashed var(--accent)' : '1px dashed rgba(255,255,255,0.3)',
        zIndex: isSelected ? 10 : 5,
        cursor: 'move',
        background: 'rgba(255,255,255,0.05)',
      }}
    >
      <canvas ref={canvasRef} style={{ width: '100%', height: '100%', display: 'block', pointerEvents: 'none' }} />
    </div>
  );
}

// --- Main Component ---
export default function LaserDotEngraver({ uploadFolder = 'laser' }) {
  const { connectionStatus, espInfo, sendWebSocketMessage } = useConnection?.() || {};
  const targetUploadFolder = uploadFolder === 'laser_dot' ? 'laser' : (uploadFolder || 'laser');

  const [items, setItems] = useState([]); // [{ id, name, image, settings, grid, originalSize }]
  const [activeId, setActiveId] = useState(null);
  const [view, setView] = useState({ x: 0, y: 0, scale: 2.0 });

  const [isProcessing, setIsProcessing] = useState(false);
  const [isUploading, setIsUploading] = useState(false);
  const [lastGeneratedGcode, setLastGeneratedGcode] = useState(null);
  const [showGcodeDialog, setShowGcodeDialog] = useState(false);
  const [isSending, setIsSending] = useState(false);
  const [zJogStep, setZJogStep] = useState(1);
  const [machineZ, setMachineZ] = useState(0);

  const [dragMode, setDragMode] = useState('NONE'); // 'NONE' | 'VIEW' | 'IMAGE'
  const lastMousePos = useRef({ x: 0, y: 0 });
  const dragItemIdRef = useRef(null);

  const fileInputRef = useRef(null);
  const containerRef = useRef(null);
  const pendingUploadsRef = useRef(0);
  const debounceTimerRef = useRef(null);

  const activeItem = items.find((i) => i.id === activeId);

  const parsePosResponse = (message) => {
    if (!message || typeof message !== 'string') return null;
    const m = message.trim().match(/POS:\s*([\d.-]+)\s*,\s*([\d.-]+)\s*,\s*([\d.-]+)(?:\s*\|\s*([\d.-]+)\s*,\s*([\d.-]+)\s*,\s*([\d.-]+))?/i);
    if (!m) return null;
    return {
      machine: {
        x: parseFloat(m[1]) || 0,
        y: parseFloat(m[2]) || 0,
        z: parseFloat(m[3]) || 0,
      },
    };
  };

  useEffect(() => {
    const onWs = (event) => {
      const { message, type } = event.detail || {};
      if (type !== 'RX') return;
      const posData = parsePosResponse(message);
      if (posData) setMachineZ(round1(posData.machine.z));
    };
    window.addEventListener('websocket-message', onWs);
    return () => window.removeEventListener('websocket-message', onWs);
  }, []);

  const readCurrentZ = () => {
    if (connectionStatus !== 'connected' || !sendWebSocketMessage) return;
    sendWebSocketMessage('#POS');
  };

  const jogZ = (dir) => {
    if (connectionStatus !== 'connected' || !sendWebSocketMessage) return;
    const step = Math.max(0.1, Number(zJogStep) || 0.1);
    const targetZ = round1(machineZ + dir * step);
    sendWebSocketMessage(`G0 Z${targetZ.toFixed(1)}`);
    setMachineZ(targetZ);
  };

  const setWorkZFromMachine = () => {
    if (!activeItem) return;
    updateSetting('workZ', machineZ);
  };

  // --- Image processing (debounced when settings change) ---
  const recomputeGrid = (item) => {
    if (!item || !item.image) return item;
    const grid = imageToDotGrid(item.image, item.settings);
    return { ...item, grid };
  };

  const scheduleRecompute = (id) => {
    if (debounceTimerRef.current) clearTimeout(debounceTimerRef.current);
    debounceTimerRef.current = setTimeout(() => {
      setItems((prev) => prev.map((it) => (it.id === id ? recomputeGrid(it) : it)));
    }, 120);
  };

  // --- File handling ---
  const handleFile = (e) => {
    const files = e.target.files;
    if (!files || files.length === 0) return;
    const imgFiles = Array.from(files).filter((f) => /\.(png|jpe?g|bmp|gif|webp)$/i.test(f.name));
    if (imgFiles.length === 0) {
      alert('Please select image files (PNG, JPG, BMP, GIF, WEBP).');
      e.target.value = '';
      return;
    }
    pendingUploadsRef.current = imgFiles.length;
    setIsUploading(true);
    imgFiles.forEach((file) => {
      const reader = new FileReader();
      reader.onload = (ev) => {
        const img = new Image();
        img.onload = () => {
          const initialWidth = 100;
          const aspect = img.naturalWidth / img.naturalHeight || 1;
          const initialHeight = round1(initialWidth / aspect);
          const id = createItemId();
          const offset = items.length * 22;
          const settings = {
            ...DEFAULT_SETTINGS,
            width: initialWidth,
            height: initialHeight,
            posX: Math.max(-250, -offset),
            posY: Math.min(BED_HEIGHT_MM - initialHeight, offset),
          };
          const newItem = recomputeGrid({
            id,
            name: file.name.replace(/\.[^.]+$/, ''),
            image: img,
            originalSize: { w: img.naturalWidth, h: img.naturalHeight },
            settings,
            grid: { dots: [], cols: 0, rows: 0 },
          });
          setItems((prev) => [...prev, newItem]);
          setActiveId(id);
          pendingUploadsRef.current -= 1;
          if (pendingUploadsRef.current === 0) setIsUploading(false);
        };
        img.onerror = () => {
          pendingUploadsRef.current -= 1;
          if (pendingUploadsRef.current === 0) setIsUploading(false);
        };
        img.src = ev.target.result;
      };
      reader.onerror = () => {
        pendingUploadsRef.current -= 1;
        if (pendingUploadsRef.current === 0) setIsUploading(false);
      };
      reader.readAsDataURL(file);
    });
    e.target.value = '';
  };

  const updateSetting = (key, value) => {
    if (!activeId) return;
    const numVal = typeof value === 'number' && !Number.isNaN(value) ? round1(value) : value;
    setItems((prev) =>
      prev.map((it) => {
        if (it.id !== activeId) return it;
        const nextSettings = { ...it.settings, [key]: numVal };
        if (it.settings.keepProportions && it.originalSize.w > 0 && (key === 'width' || key === 'height')) {
          const aspect = it.originalSize.w / it.originalSize.h;
          if (key === 'width') nextSettings.height = round1(numVal / aspect);
          if (key === 'height') nextSettings.width = round1(numVal * aspect);
        }
        return { ...it, settings: nextSettings };
      })
    );
    // Settings that affect the dot grid -> debounced recompute.
    // (laserPower and dwell don't change the grid; they're applied at G-code generation time.)
    const affectsGrid = ['width', 'height', 'dotSpacing', 'whiteThreshold', 'invert'];
    if (affectsGrid.includes(key)) scheduleRecompute(activeId);
  };

  const deleteItem = (id) => {
    setItems((prev) => {
      const next = prev.filter((i) => i.id !== id);
      if (activeId === id) setActiveId(next.length ? next[0].id : null);
      return next;
    });
  };

  // --- G-code ---
  const generateGCode = async () => {
    if (items.length === 0) return;
    setIsProcessing(true);
    await new Promise((r) => setTimeout(r, 30));
    try {
      // Make sure all grids are up-to-date
      const refreshed = items.map((it) => (it.image ? recomputeGrid(it) : it));
      setItems(refreshed);
      const code = generateLaserDotGCode(refreshed);
      setLastGeneratedGcode(code);
      setShowGcodeDialog(true);
    } catch (err) {
      console.error(err);
      alert('Error generating G-code');
    } finally {
      setIsProcessing(false);
    }
  };

  const handleDownloadGcode = () => {
    if (!lastGeneratedGcode) return;
    const blob = new Blob([lastGeneratedGcode], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `laser_dot_${items.length}img.gcode`;
    a.click();
    URL.revokeObjectURL(url);
    setShowGcodeDialog(false);
  };

  const handleSendToDevice = async () => {
    if (!lastGeneratedGcode) return;
    const baseUrl = espInfo?.baseUrl;
    if (!baseUrl) {
      alert('Connect to a device first (use the connection menu).');
      return;
    }
    if (typeof uploadGcodeFile !== 'function') {
      alert('Send to device is not available in this environment.');
      return;
    }
    const rawName = window.prompt('Enter file name (.gcode will be added automatically):', `laser_dot_${items.length}img`);
    if (rawName == null || String(rawName).trim() === '') return;
    let fileName = String(rawName).trim();
    if (!fileName.toLowerCase().endsWith('.gcode')) fileName += '.gcode';
    setIsSending(true);
    try {
      const file = new File([lastGeneratedGcode], fileName, { type: 'text/plain' });
      await uploadGcodeFile(baseUrl, file, targetUploadFolder);
      alert(`G-code sent to device.\nSaved as: ${targetUploadFolder}/${fileName}`);
      setShowGcodeDialog(false);
    } catch (e) {
      console.error(e);
      alert(e?.message || 'Failed to send G-code to device.');
    } finally {
      setIsSending(false);
    }
  };

  // --- Workspace interactions ---
  const handleWheel = (e) => {
    e.preventDefault();
    const delta = -Math.sign(e.deltaY) * 0.1;
    setView((prev) => ({ ...prev, scale: Math.max(0.2, Math.min(prev.scale + delta, 10)) }));
  };

  const handleMouseDown = (e) => {
    const itemEl = e.target.closest('[data-ldot-item]');
    if (itemEl && e.button === 0) {
      e.stopPropagation();
      const id = itemEl.dataset.id;
      setActiveId(id);
      dragItemIdRef.current = id;
      setDragMode('IMAGE');
      lastMousePos.current = { x: e.clientX, y: e.clientY };
      return;
    }
    if (e.button === 0) {
      setDragMode('VIEW');
      lastMousePos.current = { x: e.clientX, y: e.clientY };
    }
  };

  const handleMouseMove = (e) => {
    if (dragMode === 'NONE') return;
    const dx = e.clientX - lastMousePos.current.x;
    const dy = e.clientY - lastMousePos.current.y;
    lastMousePos.current = { x: e.clientX, y: e.clientY };
    if (dragMode === 'VIEW') {
      setView((prev) => ({ ...prev, x: prev.x + dx, y: prev.y + dy }));
    } else if (dragMode === 'IMAGE' && dragItemIdRef.current) {
      const dxMm = dx / view.scale;
      const dyMm = -dy / view.scale;
      setItems((prev) =>
        prev.map((it) => {
          if (it.id !== dragItemIdRef.current) return it;
          const s = it.settings;
          const minX = -250;
          const maxX = 250 - s.width;
          const minY = 0;
          const maxY = Math.max(0, BED_HEIGHT_MM - s.height);
          return {
            ...it,
            settings: {
              ...s,
              posX: round1(Math.max(minX, Math.min(maxX, s.posX + dxMm))),
              posY: round1(Math.max(minY, Math.min(maxY, s.posY + dyMm))),
            },
          };
        })
      );
    }
  };

  const handleMouseUp = () => setDragMode('NONE');

  const totalDots = useMemo(
    () => items.reduce((sum, it) => sum + (it.grid?.dots?.length || 0), 0),
    [items]
  );

  return (
    <div className="ldot-studio-body">
      <div id="ldot-main-container">
        {/* LEFT TOOLBAR */}
        <div className="ldot-toolbar">
          <label className="ldot-icon-btn" title="Upload images">
            &#128193;
            <input
              ref={fileInputRef}
              type="file"
              accept="image/png,image/jpeg,image/bmp,image/gif,image/webp"
              multiple
              onChange={handleFile}
              style={{ display: 'none' }}
            />
          </label>
          <button
            className="ldot-icon-btn"
            title="Reset view"
            onClick={() => {
              setItems([]);
              setActiveId(null);
              setView({ x: 0, y: 0, scale: 2 });
            }}
          >
            &#10227;
          </button>
          <div style={{ flexGrow: 1 }} />
        </div>

        {/* CENTER WORKSPACE */}
        <div
          className="ldot-workspace"
          ref={containerRef}
          onWheel={handleWheel}
          onMouseDown={handleMouseDown}
          onMouseMove={handleMouseMove}
          onMouseUp={handleMouseUp}
          onMouseLeave={handleMouseUp}
          style={{ cursor: dragMode === 'VIEW' ? 'grabbing' : 'grab', userSelect: 'none' }}
        >
          <div
            id="ldot-bed"
            style={{
              width: `${BED_WIDTH_MM * view.scale}px`,
              height: `${BED_HEIGHT_MM * view.scale}px`,
              backgroundColor: 'rgba(232,232,232,0.95)',
              boxShadow: '0 10px 30px rgba(0,0,0,0.4)',
              position: 'absolute',
              transform: 'translate(-50%, -50%)',
              left: `calc(50% + ${view.x}px)`,
              top: `calc(50% + ${view.y}px)`,
              backgroundImage:
                'linear-gradient(rgba(200,200,200,0.8) 1px, transparent 1px), linear-gradient(90deg, rgba(200,200,200,0.8) 1px, transparent 1px)',
              backgroundSize: `${10 * view.scale}px ${10 * view.scale}px`,
              backgroundPosition: 'center bottom',
              transition: dragMode === 'NONE' ? 'width 0.1s, height 0.1s' : 'none',
              borderRadius: '8px',
            }}
          >
            <div style={{ position: 'absolute', top: 0, bottom: 0, left: '50%', width: 0, borderLeft: '2px solid #e74c3c', zIndex: 0, pointerEvents: 'none' }} />
            <div style={{ position: 'absolute', bottom: 0, left: 0, right: 0, height: 0, borderBottom: '2px solid #2ecc71', zIndex: 0, pointerEvents: 'none' }} />
            <div style={{ position: 'absolute', left: 4, bottom: 4, fontSize: 10, color: '#666', pointerEvents: 'none' }}>-250,0</div>
            <div style={{ position: 'absolute', left: '50%', bottom: 4, transform: 'translateX(-50%)', fontSize: 10, color: '#666', pointerEvents: 'none' }}>0,0</div>
            <div style={{ position: 'absolute', right: 4, bottom: 4, fontSize: 10, color: '#666', pointerEvents: 'none' }}>250,0</div>

            {items.map((item) => (
              <DotPreview
                key={item.id}
                item={item}
                scale={view.scale}
                isSelected={activeId === item.id}
              />
            ))}

            {isUploading && (
              <div style={{ position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'rgba(0,0,0,0.5)', color: 'var(--accent)', fontSize: 16, fontWeight: 'bold', pointerEvents: 'none', zIndex: 50 }}>
                Loading image…
              </div>
            )}
            {items.length === 0 && !isUploading && (
              <div style={{ position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--text-muted)', fontSize: 14, pointerEvents: 'none' }}>
                Load an image (PNG / JPG)
              </div>
            )}
          </div>
        </div>

        {/* RIGHT SETTINGS */}
        <div className="ldot-settings">
          {items.length === 0 && (
            <div style={{ position: 'absolute', top: 0, left: 0, width: '100%', height: '100%', background: 'rgba(0,0,0,0.4)', zIndex: 100, display: 'flex', justifyContent: 'center', alignItems: 'center', fontWeight: 'bold', color: 'var(--text-muted)', backdropFilter: 'blur(4px)' }}>
              Load an image
            </div>
          )}

          <div style={{ padding: 20, overflowY: 'auto', flexGrow: 1 }}>
            <button
              className="ldot-full-width-btn"
              onClick={generateGCode}
              disabled={items.length === 0 || isProcessing}
              style={{ marginBottom: 12 }}
            >
              {isProcessing ? 'PROCESSING...' : 'GENERATE G-CODE'}
            </button>

            {totalDots > 0 && (
              <div className="ldot-hint" style={{ marginTop: 0, marginBottom: 12 }}>
                Total burn dots: <b style={{ color: 'var(--accent)' }}>{totalDots.toLocaleString()}</b>
              </div>
            )}

            {showGcodeDialog && lastGeneratedGcode && (
              <div
                style={{ position: 'fixed', inset: 0, zIndex: 9999, display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'rgba(0,0,0,0.5)', padding: 20 }}
                onClick={(e) => { if (e.target === e.currentTarget) setShowGcodeDialog(false); }}
              >
                <div
                  style={{ background: 'var(--card-bg, #1a1a2e)', borderRadius: 12, padding: 24, maxWidth: 360, width: '100%', boxShadow: '0 8px 32px rgba(0,0,0,0.4)', border: '1px solid rgba(255,255,255,0.1)' }}
                  onClick={(e) => e.stopPropagation()}
                >
                  <div style={{ fontSize: 16, fontWeight: 600, marginBottom: 8 }}>G-code ready</div>
                  <div style={{ fontSize: 13, color: 'var(--text-muted)', marginBottom: 20 }}>What would you like to do?</div>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
                    <button type="button" className="ldot-full-width-btn" onClick={handleDownloadGcode}>
                      Download
                    </button>
                    <button
                      type="button"
                      className="ldot-full-width-btn"
                      onClick={handleSendToDevice}
                      disabled={connectionStatus !== 'connected' || isSending}
                      style={{ opacity: connectionStatus === 'connected' ? 1 : 0.7 }}
                    >
                      {isSending ? 'SENDING...' : 'Send to device'}
                    </button>
                    <button
                      type="button"
                      onClick={() => setShowGcodeDialog(false)}
                      style={{ background: 'none', border: '1px solid rgba(255,255,255,0.2)', color: 'var(--text-muted)', padding: '10px 16px', borderRadius: 8, cursor: 'pointer', fontSize: 13 }}
                    >
                      Cancel
                    </button>
                  </div>
                </div>
              </div>
            )}

            {items.length > 0 && (
              <div style={{ marginTop: 8, marginBottom: 8, maxHeight: 120, overflowY: 'auto' }}>
                {items.map((it) => (
                  <div
                    key={it.id}
                    onClick={() => setActiveId(it.id)}
                    style={{
                      display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                      padding: '6px 8px', marginBottom: 4, borderRadius: 6, cursor: 'pointer',
                      background: activeId === it.id ? 'rgba(0,210,255,0.2)' : 'rgba(255,255,255,0.05)',
                      border: activeId === it.id ? '1px solid var(--accent)' : '1px solid transparent',
                    }}
                  >
                    <span style={{ fontSize: 12, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', maxWidth: 180 }}>{it.name}</span>
                    <button
                      type="button"
                      onClick={(ev) => { ev.stopPropagation(); deleteItem(it.id); }}
                      style={{ background: 'none', border: 'none', color: 'var(--text-muted)', cursor: 'pointer', padding: '0 4px', fontSize: 14 }}
                      title="Remove"
                    >
                      ×
                    </button>
                  </div>
                ))}
              </div>
            )}

            {activeItem && (
              <>
                <div className="ldot-section-header">Dimensions (mm)</div>
                <div className="ldot-control-group">
                  <label>Width:</label>
                  <input type="number" step="0.1" value={activeItem.settings.width}
                    onChange={(e) => updateSetting('width', parseFloat(e.target.value) || 0)} />
                </div>
                <div className="ldot-control-group">
                  <label>Height:</label>
                  <input type="number" step="0.1" value={activeItem.settings.height}
                    onChange={(e) => updateSetting('height', parseFloat(e.target.value) || 0)} />
                </div>
                <div className="ldot-control-group">
                  <label>Keep proportions:</label>
                  <input type="checkbox" checked={activeItem.settings.keepProportions}
                    onChange={(e) => updateSetting('keepProportions', e.target.checked)} />
                </div>

                <div className="ldot-section-header">Position (mm)</div>
                <div className="ldot-control-group">
                  <label>Pos X:</label>
                  <input type="number" step="0.1" value={activeItem.settings.posX}
                    onChange={(e) => updateSetting('posX', parseFloat(e.target.value) || 0)} />
                </div>
                <div className="ldot-control-group">
                  <label>Pos Y:</label>
                  <input type="number" step="0.1" value={activeItem.settings.posY}
                    onChange={(e) => updateSetting('posY', parseFloat(e.target.value) || 0)} />
                </div>

                <div className="ldot-section-header">Dot engraving</div>
                <div className="ldot-control-group">
                  <label>Dot spacing (mm):</label>
                  <input type="number" step="0.05" min="0.05" value={activeItem.settings.dotSpacing}
                    onChange={(e) => updateSetting('dotSpacing', Math.max(0.05, parseFloat(e.target.value) || 0.05))} />
                </div>
                <div className="ldot-control-group">
                  <label>Laser power (S):</label>
                  <input type="number" step="1" min="0" max="65535" value={activeItem.settings.laserPower}
                    onChange={(e) => updateSetting('laserPower', parseFloat(e.target.value) || 0)} />
                </div>
                <div className="ldot-control-group">
                  <label>Dwell (ms):</label>
                  <input type="number" step="1" min="1" value={activeItem.settings.dwell}
                    onChange={(e) => updateSetting('dwell', parseFloat(e.target.value) || 1)} />
                </div>
                <div className="ldot-control-group">
                  <label>White threshold:</label>
                  <input type="number" step="1" min="1" max="255" value={activeItem.settings.whiteThreshold}
                    onChange={(e) => updateSetting('whiteThreshold', parseFloat(e.target.value) || 1)} />
                </div>
                <div className="ldot-control-group">
                  <label>Travel speed:</label>
                  <input type="number" step="100" value={activeItem.settings.travelSpeed}
                    onChange={(e) => updateSetting('travelSpeed', parseFloat(e.target.value) || 0)} />
                </div>
                <div className="ldot-control-group">
                  <label>Work Z (mm):</label>
                  <input
                    type="number"
                    step="0.1"
                    value={activeItem.settings.workZ ?? 0}
                    onChange={(e) => updateSetting('workZ', parseFloat(e.target.value) || 0)}
                  />
                </div>
                <div className="ldot-control-group" style={{ display: 'block' }}>
                  <label style={{ display: 'block', marginBottom: 6 }}>Z jog (set before Work Z):</label>
                  <div style={{ display: 'flex', gap: 6, alignItems: 'center', justifyContent: 'flex-end', flexWrap: 'wrap' }}>
                    <span style={{ fontSize: 11, color: 'var(--text-muted)' }}>Machine Z: {machineZ.toFixed(1)}</span>
                    <input
                      type="number"
                      step="0.1"
                      min="0.1"
                      value={zJogStep}
                      onChange={(e) => setZJogStep(Math.max(0.1, parseFloat(e.target.value) || 0.1))}
                      style={{ width: 72 }}
                    />
                    <button type="button" className="ldot-full-width-btn" style={{ width: 'auto', padding: '6px 10px' }} onClick={() => jogZ(-1)} disabled={connectionStatus !== 'connected'}>Z-</button>
                    <button type="button" className="ldot-full-width-btn" style={{ width: 'auto', padding: '6px 10px' }} onClick={() => jogZ(1)} disabled={connectionStatus !== 'connected'}>Z+</button>
                    <button type="button" className="ldot-full-width-btn" style={{ width: 'auto', padding: '6px 10px' }} onClick={readCurrentZ} disabled={connectionStatus !== 'connected'}>Read Z</button>
                    <button type="button" className="ldot-full-width-btn" style={{ width: 'auto', padding: '6px 10px' }} onClick={setWorkZFromMachine}>Use current</button>
                  </div>
                </div>
                <div className="ldot-control-group">
                  <label>Negative image:</label>
                  <input type="checkbox" checked={activeItem.settings.invert}
                    onChange={(e) => updateSetting('invert', e.target.checked)} />
                </div>
                <div className="ldot-control-group">
                  <label>Zigzag travel:</label>
                  <input type="checkbox" checked={activeItem.settings.zigzag}
                    onChange={(e) => updateSetting('zigzag', e.target.checked)} />
                </div>
                <div className="ldot-control-group">
                  <label>Dwell unit:</label>
                  <select
                    value={activeItem.settings.dwellUnit}
                    onChange={(e) => updateSetting('dwellUnit', e.target.value)}
                    style={{ float: 'right', padding: '2px 4px', border: '1px solid var(--glass-border)', borderRadius: 4, background: 'rgba(0,0,0,0.3)', color: 'var(--text)', fontSize: 11 }}
                  >
                    <option value="ms">ms (Marlin: G4 P&lt;ms&gt;)</option>
                    <option value="s">s (GRBL: G4 P&lt;sec&gt;)</option>
                  </select>
                </div>
              </>
            )}

            <div className="ldot-hint">
              Load an image. Each pixel becomes a laser dot — darker pixels burn at higher
              power (S is scaled from 0..255 grayscale up to your "Laser power" max).
              Dwell time is the same for every dot.
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
